
"use client";

import { useEffect, useState, useRef } from "react";
import Image from "next/image";
import Link from "next/link";
import { Sparkles, ChevronLeft, ChevronRight } from "lucide-react";

interface CurationBook {
    id: string;
    title: string;
    imageUrl?: string;
    category?: string;
    recommendation?: string;
    coupangLink?: string;
    [key: string]: unknown;
}

function CategoryCarousel({ category, books }: { category: string, books: CurationBook[] }) {
    const scrollRef = useRef<HTMLDivElement>(null);

    const scroll = (direction: 'left' | 'right') => {
        if (scrollRef.current) {
            const { current } = scrollRef;
            const scrollAmount = current.clientWidth * 0.8;
            current.scrollBy({ left: direction === 'left' ? -scrollAmount : scrollAmount, behavior: 'smooth' });
        }
    };

    return (
        <div className="space-y-4">
            <div className="flex items-center justify-between px-2">
                <h3 className="text-xl md:text-2xl font-bold text-white font-serif">{category}</h3>
                <div className="flex gap-2">
                    <button onClick={() => scroll('left')} className="p-2 rounded-full bg-white/5 hover:bg-white/10 text-white transition-colors" aria-label="이전">
                        <ChevronLeft className="w-4 h-4" />
                    </button>
                    <button onClick={() => scroll('right')} className="p-2 rounded-full bg-white/5 hover:bg-white/10 text-white transition-colors" aria-label="다음">
                        <ChevronRight className="w-4 h-4" />
                    </button>
                </div>
            </div>

            <div
                ref={scrollRef}
                className="flex gap-4 overflow-x-auto snap-x snap-mandatory pb-4 [&::-webkit-scrollbar]:hidden"
                style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}
            >
                {books.map((book, i) => (
                    <div key={book.id} className="w-[calc(50%-0.5rem)] md:w-[calc(25%-0.75rem)] shrink-0 snap-start">
                        <Link href={book.coupangLink || "#"} target="_blank" rel="noopener noreferrer" className="group space-y-4 block">
                            <div className="aspect-[1/1.5] relative rounded-sm overflow-hidden shadow-2xl border border-white/5 group-hover:shadow-accent/20 transition-all duration-500 group-hover:-translate-y-2">
                                {book.imageUrl ? (
                                    <Image
                                        src={book.imageUrl.replace("coversum", "cover500")}
                                        alt={book.title}
                                        fill
                                        className="object-cover transition-transform duration-700 group-hover:scale-110"
                                        referrerPolicy="no-referrer"
                                    />
                                ) : (
                                    <div className="w-full h-full bg-slate-800 flex items-center justify-center text-gray-500">No Image</div>
                                )}
                                <div className="absolute inset-0 bg-gradient-to-t from-black via-black/60 to-transparent opacity-90" />
                                <div className="absolute bottom-4 left-4 right-4 text-left">
                                    <div className="text-[10px] text-accent font-bold uppercase tracking-tighter mb-1">Pick {i + 1}</div>
                                    <div className="text-white font-bold text-sm leading-tight drop-shadow-md">{book.title}</div>
                                </div>
                            </div>
                            <div className="space-y-1">
                                <div className="bg-white/5 border border-white/10 rounded-md p-3 hover:bg-white/10 transition-colors">
                                    <p className="text-xs text-gray-300 font-light leading-relaxed">
                                        {book.recommendation}
                                    </p>
                                </div>
                            </div>
                        </Link>
                    </div>
                ))}
            </div>
        </div>
    );
}

interface Curation {
    id: string;
    theme: string;
    title: string;
    description: string;
    books: CurationBook[];
}

interface CurationProps {
    id?: string;
}

export default function CurationSection({ id }: CurationProps = {}) {
    const [curation, setCuration] = useState<Curation | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        async function fetchLatestCuration() {
            try {
                // Fetch from static JSON file generated by sync pipeline
                const response = await fetch("/data/bookfit-choice.json");
                if (response.ok) {
                    const data = await response.json();
                    if (data && data.books && data.books.length > 0) {
                        setCuration(data);
                    }
                } else {
                    // Fallback to API if JSON is not found yet
                    const apiResponse = await fetch("/api/curation");
                    if (apiResponse.ok) {
                        const apiData = await apiResponse.json();
                        if (apiData && apiData.length > 0) {
                            setCuration(apiData[0]);
                        }
                    }
                }
            } catch (error) {
                console.error("Failed to fetch curation", error);
            } finally {
                setLoading(false);
            }
        }
        fetchLatestCuration();
    }, []);

    if (loading) {
        return (
            <div id={id} className="w-full py-20 flex justify-center">
                <div className="w-8 h-8 border-2 border-accent/20 border-t-accent rounded-full animate-spin"></div>
            </div>
        );
    }

    if (!curation) {
        return (
            <section id={id} className="w-full py-24 px-6 max-w-6xl mx-auto text-center border-y border-white/5 bg-white/2">
                <div className="space-y-6">
                    <h2 className="text-3xl font-serif text-white opacity-50">BookFit Choice</h2>
                    <p className="text-gray-500 font-light">곧 새로운 큐레이션이 공개됩니다. 잠시만 기다려 주세요!</p>
                    <div className="flex justify-center gap-8 opacity-20 grayscale pointer-events-none">
                        {[1, 2, 3].map(i => (
                            <div key={i} className="aspect-[1/1.5] w-32 bg-slate-800 rounded shadow-2xl" />
                        ))}
                    </div>
                </div>
            </section>
        );
    }

    return (
        <section id={id} className="w-full py-24 px-6 max-w-6xl mx-auto">
            <div className="flex flex-col gap-10">
                {/* Header: Title & Description */}
                <div className="text-center max-w-3xl mx-auto space-y-4">
                    <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-accent/10 border border-accent/20 text-accent text-xs font-bold uppercase tracking-widest mb-2">
                        <Sparkles className="w-3 h-3" /> Monthly Selection
                    </div>
                    <h2 className="text-3xl md:text-5xl font-black text-white font-serif leading-tight">
                        BookFit Choice
                    </h2>
                    <p className="text-lg text-gray-400 font-light leading-relaxed whitespace-pre-line">
                        이번 달, 북핏의 큐레이터들이 선정한 깊이 있는 사유의 조각들입니다.
                    </p>
                </div>

                {/* Books Grouped by Category (Swiper) */}
                <div className="space-y-12">
                    {Object.entries(
                        curation.books.reduce((acc, book) => {
                            const category = book.category || '기타';
                            if (!acc[category]) acc[category] = [];
                            acc[category].push(book);
                            return acc;
                        }, {} as Record<string, CurationBook[]>)
                    ).map(([category, books]) => (
                        <CategoryCarousel key={category} category={category} books={books as CurationBook[]} />
                    ))}
                </div>
            </div>

            {/* View All Button */}
            <div className="mt-12 flex justify-center">
                <Link href="/curation">
                    <button className="px-8 py-3 rounded-full border border-white/20 hover:bg-white/10 text-white font-medium transition-all group flex items-center gap-2">
                        View All Collection
                        <Sparkles className="w-4 h-4 text-accent opacity-50 group-hover:opacity-100 transition-opacity" />
                    </button>
                </Link>
            </div>
        </section>
    );
}
